# -*- coding: utf-8 -*-
"""Project_Blur.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M1V1ANe3PknNPqXrXArSxOAh6DlKygat
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/ultralytics/yolov5  # clone
# %cd yolov5
# %pip install -qr requirements.txt  # install

import torch
from yolov5 import utils
display = utils.notebook_init()  # checks

"""The two cells under was to make a copy of the yolov5 folder and convert it to zip, and then download it.
* They can be ignored unless you want to download again (cell over have to be run before)
"""

!zip -r /content/yolov5.zip /content/yolov5/

from google.colab import files
files.download('/content/yolov5.zip')

"""Drag yolov5.zip into collab files if you did not run the cell code that cloned the yolov5 folder from git
* Run code under after it appears
"""

!unzip -q /content/yolov5.zip -d ../

# Drag Color, Gray and Blur zip into collab files, then run code cell
!unzip -q /content/Color.zip -d ../
!unzip -q /content/Gray.zip -d ../
!unzip -q /content/Blur.zip -d ../

"""Go to /content/yolov5/data/hyps/hyp.scratch-low.yaml to edit learning rate.
  

*   lr0 is initial learning rate
*   lrf is final OneCycleLR learning rate (lr0 * lrf)

Go to Gray, Gray, and cat_blur folder, and move the .yaml files to /yolov5/data
* They should appear right over yolov5 folder(just wait abit)
* If not, go up one level (double click the .. at the top in file section, should be above yolov5 folder)
* Move them into content folder
"""

# Training the model with 30 epochs, takes around 4.2 hours
!python /content/yolov5/train.py --img 640 --batch 16 --epochs 30 --data Blur.yaml --weights yolov5s.pt --cache

!python /content/yolov5/detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.35 --source ../cat_blur/test/images

!python /content/yolov5/detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.35 --source ../Color/test/images

!python /content/yolov5/detect.py --weights runs/train/exp/weights/best.pt --img 640 --conf 0.35 --source ../Gray/test/images

!zip -r /content/detect_blur.zip /content/yolov5/runs/detect

from google.colab import files
files.download('/content/detect_blur.zip')